### ISSUE TITLE
No documentation!

### ISSUE THREAD

**Issue by mst101** [ktsn/vue-range-slider#10]
Can you please explain how to use this component? Thanks

**Comment by ktsn** [comment]
I'll write that later. BTW, you can learn that by [example](https://github.com/ktsn/vue-range-slider/blob/master/example/App.vue#L3-L10) for now.

**Comment by mst101** [comment]
OK. I’ve just got it to work and am currently adding a second knob to the slider as I want to use it for earliest and latest departure times. Almost there now...

Nice piece of Vue 2.0 work, thank you!

PS. I’m sure it’s blasphemy to the Javascript gods, but in my ignorance of Flow, the only way I could get it to the .vue file to compile correctly (using Laravel 5.3) was to strip out all the flow type information e.g. :number  etc. Anyway – it works!

**Comment by ktsn** [comment]
I've updated README. Thanks for your feedback!

Sorry, I'm not familiar with the `.vue` build environment of Laravel as I've never use it. If you can use Babel in the build process of `.vue` file, maybe you can strip type annotations by using [babel-plugin-transform-flow-strip-types](https://babeljs.io/docs/plugins/transform-flow-strip-types/).

**Comment by mst101** [comment]
That's great. Thanks very much.
