### ISSUE TITLE
Support for 2 nodes in a slider for setting a range

### ISSUE THREAD

**Issue by hiddendragonXVII** [ktsn/vue-range-slider#13]
functionality like this would be really handy
http://jqueryui.com/slider/#range

**Comment by ktsn** [comment]
I'm afraid, I'm unwilling to implement this feature since the purpose of this component is like polyfill of native `input[type=range]` element. And also I cannot take a time to add new feature for this now.
But if you would like to implement the feature, PR is welcome.

**Comment by ktsn** [comment]
Rethinking about this, supporting multiple knob makes this component too complex, so I would not go for it.
