### ISSUE TITLE
Move slider dot after clicking the slider

### ISSUE THREAD

**Issue by LTroya** [ktsn/vue-range-slider#18]
Is there a way to achieve this? The only way I see to set a value via UI is moving the slider dot

**Comment by rolandalla** [comment]
Hi @LTroya  Did you find any solution ? Please let me know

**Comment by Ben-Mack** [comment]
Yes, Please add this feature, this is must have for range slider.

**Comment by Cathy007US** [comment]
Is there anyone updating this plug-in and clicking the scroll bar to move the slider
