### ISSUE TITLE
Maximum not reachable if step set to more than 1

### ISSUE THREAD

**Issue by janbalaz** [ktsn/vue-range-slider#23]
Hi,
it seems maximum value is not reachable in some situations, for example lets have following:
min = 23
max = 100
step 10

In above case maximum reachable by sliding is 93. I believe correct for last step would be to reach the end, but I might be wrong.
It is achievable by setting step to 1, but that breaks purpose of step.
I apologize if you don't consider this a bug.

**Comment by ktsn** [comment]
This is intentional since vue-range-slider is meant to be a superset of native input:range element.
