### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by Audesi** [ktsn/vue-range-slider#24]
I'm getting this warning in Chrome:

vue-range-slider.cjs.js:136 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
dragMove @ vue-range-slider.cjs.js:136
boundFn @ vue.common.js:191
touchmove @ vue-range-slider.cjs.js:107
(anonymous) @ vue-range-slider.cjs.js:33

**Comment by ktsn** [comment]
fixed in v0.3.2
