### ISSUE TITLE
Adding the name property to the $emit events

### ISSUE THREAD

**Issue by jameswhayman** [ktsn/vue-range-slider#37]
Would it be possible to add the element's name property to the $emit input and $emit change events, so the slider emitting the event can be more easily identified?

i.e.
`this.$emit('input', {name: this.name, value: value})`
`this.$emit('change', {name: this.name, value: value})`

**Comment by ktsn** [comment]
What is the use case for that? I think you already know the `name` value without including event arguments since you pass the value as the range slider prop.

**Comment by jameswhayman** [comment]
I'm still a Vue newbie so maybe there's another way to do it? Apologies if I've missed something obvious.

I've got a few sliders on my app and I'm listening for the "input" event on each one so I can perform some updates on another part of the app, depending on which slider emitted the event.

At the moment the "input" event is only returning the value from the range slider, and I don't know how I can get the "name" property of the range slider that emitted that value unless it's included as part of the $emit function.

**Comment by ktsn** [comment]
Just pass the name value to your input listener.

```vue
<RangeSlider :name="yourName" @input="onInput(yourName, arguments[0])"/>
```
