### ISSUE TITLE
How to change slider colors

### ISSUE THREAD

**Issue by kapdom** [ktsn/vue-range-slider#39]
Hi.
I try to change a rail color but without success.

`.slider .range-slider-fill{
        background-color: #ff9c00;
    }`
I can change slider width but no color.
What am I doing wrong?
Thx.

**Comment by ktsn** [comment]
They are defined as SCSS variable. https://github.com/ktsn/vue-range-slider/blob/master/src/RangeSlider.vue#L157-L159
See [here](https://github.com/ktsn/vue-range-slider#overwrite-default-styles) to know how to customize them.

**Comment by kapdom** [comment]
I have no idea about SCSS, so can you show me how to change this color it in vue?
Thank you.
