### ISSUE TITLE
module is undefined

### ISSUE THREAD

**Issue by Jp3rd** [ktsn/vue-range-slider#42]
![image](https://user-images.githubusercontent.com/9080342/49502538-38762700-f8b0-11e8-824e-ad480580cea8.png)

I am getting this error when I use directly to my html file using a CDN.

**Comment by ktsn** [comment]
`vue-range-slider.cjs.js` is meant to be used with module bundler (webpack, rollup, browserify, etc). If you use it directly in browsers, please use `vue-range-slider.js` or `vue-range-slider.min.js`
https://unpkg.com/vue-range-slider@0.6.0/dist/vue-range-slider.js
https://unpkg.com/vue-range-slider@0.6.0/dist/vue-range-slider.min.js
